#
# ChestIcon
#  @author Robby Duke
#  @date   01/09/2015
#

name: 'ChestIcon'
version: 1.1
description: 'ChestShop integrated implementation of visible item sales.'

author: 'Robby Duke'
authors: ['NoEff3x', 'jacklink01']
website: https://github.com/VoidTeam/chesticon

main: net.voidteam.cicon.ChestIcon
database: false
depend: ['ChestShop']

commands:
  chesticon:
    description: ]Type /chesticon for more information.
    usage: /<command> help for more information.
permissions:
  itemstay.admin:
    description: Allows user to reload or remove ChestIcons.
    default: op